Dear Student,

I'm happy to announce that you've managed to get **4** out of 8 points for this assignment.
<details><summary>You have already managed to pass 4 tests, so that is encouraging!</summary>&emsp;☑&nbsp;[1p]&nbsp;func_call_default<br>&emsp;☑&nbsp;[1p]&nbsp;neg<br>&emsp;☑&nbsp;[1p]&nbsp;func_call<br>&emsp;☑&nbsp;[1p]&nbsp;ifelse</details>

There still exist some issues that should be addressed before the deadline: **2023-11-23 08:00:00 CET (+0100)**. For further details, please refer to the following list:

<details><summary>test_func_call_syntax_sugar.pl: unknown error. Maybe your code called &#x27;abort&#x27; or &#x27;halt&#x27;? Does it really compile?</summary></details>
<details><summary>[1p] curry_call &gt;&gt; an unexpected problem - the predicate has thrown an exception during a call `curry_call(function(nth0/4/1,[]),[1,0,2,3,4,5],_20042),curry_call(_20042,0,_20110),curry_call(_20110,[1,2,3,4,5],_20118)`</summary>&nbsp;-&nbsp;the&nbsp;exception:&nbsp;`error(type_error(nonneg,function(nth0/4/1,[[1,0,2,3,4,5],0,[1,2,3,4,5]])),_19912)`</details>
<details><summary>[1p] curry_call_syntax_sugar &gt;&gt; an unexpected problem - the predicate has thrown an exception: error(existence_error(procedure,check_curry_chain_case/4),context(check_curry_call_syntax_chain/2,_22384))</summary></details>
<details><summary>test_nested_calls.pl: unknown error. Maybe your code called &#x27;abort&#x27; or &#x27;halt&#x27;? Does it really compile?</summary></details>

-----------
I remain your faithful servant\
_Bobot_